from yacs.config import CfgNode as CN


_C = CN()
_C.INPUT = "./data/"
_C.OUTPUT = "./output/"
_C.MODEL = "GPT2"

_C.DATA = CN()
_C.DATA.DATASET_NAME = "tokenized_dataset_bert"
_C.DATA.LOAD_DATASET_FROM_DISK = False


_C.TRANSFORMER_SOLVER = CN()
_C.TRANSFORMER_SOLVER.LR = 3e-5
_C.TRANSFORMER_SOLVER.TRAIN_BATCH_SIZE = 128
_C.TRANSFORMER_SOLVER.TEST_BATCH_SIZE = 128
_C.TRANSFORMER_SOLVER.GRAD_ACC_STEPS = 2
_C.TRANSFORMER_SOLVER.GRAD_CKPT = True
_C.TRANSFORMER_SOLVER.FP16 = True
_C.TRANSFORMER_SOLVER.EPOCHS = 10
_C.TRANSFORMER_SOLVER.WEIGHT_DECAY = 1e-2

_C.BERT = CN()
_C.BERT.BACKBONE = "bert-base-cased"
_C.BERT.RESUME_FROM_CKPT = False
_C.BERT.CKPT_PATH = ""



def get_cfg_defaults():
    return _C.clone()